controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    stepper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50


stepper_trajectory_controller:
  ros__parameters:

    joints:
      - stepper_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: false

    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: true

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    constraints:
      stepper_joint:
        goal: 0.5

      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
